# Generated by Django 5.2.7 on 2025-10-22 19:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geral_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dificuldade', models.CharField(choices=[('F', 'Fácil'), ('M', 'Média'), ('D', 'Difícil')], max_length=1)),
                ('enunciado', models.TextField()),
                ('alternativas', models.JSONField(default=dict)),
                ('resposta_correta', models.CharField(max_length=5)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='questoes', to='geral_app.categoria')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_criadas', to=settings.AUTH_USER_MODEL)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='geral_app.turma')),
                ('questoes', models.ManyToManyField(related_name='avaliacoes', to='gerador_app.questao')),
            ],
        ),
        migrations.CreateModel(
            name='RespostaAluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno_id_externo', models.CharField(db_index=True, max_length=255)),
                ('resposta_aluno', models.CharField(max_length=5)),
                ('esta_correta', models.BooleanField()),
                ('avaliacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='gerador_app.avaliacao')),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gerador_app.questao')),
            ],
            options={
                'unique_together': {('avaliacao', 'questao', 'aluno_id_externo')},
            },
        ),
    ]
